
# Site settings
title: Oury
description: Your site's description here.
logo: /assets/images/image3.jpeg
show-downloads: true

# Theme settings
remote-theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme

