# title: Oury
# logo: "../assets/images/image3.png"
# show-downloads: "true"
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme 

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
title: Oury
logo: /images/image3.png
description: [A short description of your site's purpose]
show_downloads: "true"



