# title: Oury
# logo: /assets/images/image3.jpeg
# show-downloads: true
# remote-theme: pages-themes/minimal@v0.2.0

# plugins:
#   - jekyll-remote-theme

title: Oury
logo: /assets/images/image3.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
